feat: add pre-commit messages

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,4 +2,13 @@
 . "$(dirname "$0")/_/husky.sh"
 . "$(dirname "$0")/common.sh"
 
+echo "Running pre-commit hook..."
 yarn pre_commit
+echo "Running pre-commit hook..."
+
+if [ $? -eq 0 ]; then
+  echo "Pre-commit hook completed successfully."
+else
+  echo "Pre-commit hook failed."
+  exit 1
+fi
